---
title: "WHAT IS DOWN'S SYNDROME/TRISOMY 21"
description: |
  A short description of the post.
author:
  - name: Azaria Nono
date: 10-21-2019
output:
  distill::distill_article:
    self_contained: false
---

# ANALYSIS TABLE

# ARTICLE 1: WHAT IS DOWN'S SYNDROME

## Source of the article:https://www.bbc.co.uk/newsround/24708543
## Word count: 525


## II - VOCABULARY: 

Word from the text |  Synonym/definition in English |  French translation
------------------ | -----------------------------  |----------------------
disease            |       illness                  |   maladie 
speech problems    |       language difficulties    |   problème d'élocution
gene               |       heridity                 |      gène    
translocation      |       modification             |     translocation 
mosaic             |       fine art                 |     mosaique

## III - ANALYSIS TABLE ABOUT THE STUDY

**Researchers:**	

**Published in :** 21 march 2019

**General topic	:** What is down's syndrome

# Introduction 

This article is aim at bringing awerness of the condition to the general public.Explain  what the condition is about,how it occurs and especially make them know how and when they can show their support to down's syndromes victims through their daily life.

# Procedure         

   The article is very well written because, at the beginning of the article we can clearly see the writers aim which is to present and show the support to the down syndrom commmunity through the wearing of colourful socks on the 21st march . Then he went further by explaining what the condition was really about and where it came from in other to alert the general public of the humanity of the victims




# Conclusions/ discovery	
  
  In conclusion i can say that it is very important for people with a normal mental capacity to show their support to down's syndrome community so as to help them over come their daily life challenges cause as we read from the article ,these victims aren't only suffering from mental retardation but also from a particular illness due to heart , liver or lungs malformations . For this reson i strongly believe that each and every one of us must wear colorful socks every 21 march.
  
  
# Remaining questions	

* how is it perceived by others?

* can down's syndrom be treated?

* how are the poeple with this genetic condition and their family leaving?



 
