---
title: "'There is no word for Down’s syndrome in my language'"
description: |
  A short description of the post.
author:
  - name: Azaria Nono
    url: {}
date: 10-26-2019
output:
  distill::distill_article:
    self_contained: false
---


# ARTICLE 2: 'There is no word for Down’s syndrome in my language'


## Source of the article: https://www.bbc.com/news/world-africa-48252939
## Word count: 



# II - VOCABULARY: 

Word from the text |  Synonym/definition in English |  French translation
------------------ | -----------------------------  |----------------------
geared           |       accomodate                 |   adapté 
palsy   |       paralysis    |   paralysie
dwarf             |       short             |      nain   
floristry      |    blooming               |     fleuristerie 
to cast a spell        |      enchant             |  jeter un sort
googoling       |   learning disabilities    |  googler
outrageous      |   scandalizing    | outrageux

		
		
		
		

# III - ANALYSIS TABlE
**Researchers:   **                          |

**Published in :**  4 JUNE 2019


## General topic :'There is no word for Down’s syndrome in my language'

## Intoduction

This article tries to explain the difficulties encountered by down's syndrome victims relatives in our society especially in africa. This is because in african communities people believe that all what is bad or negative from their point of view is surely  due to a curse . So this article is really aim at impooving the awearness about the condition in our society


## Procedure/                what was examined	

* The article was very well structured at first through the conversation the woman had with her sit mate in the plane helped us to realise how ignored the condition was in the country to an extend that there was no word for the condition in the local language even by the doctors themselves

* Secondly, the author clearly tries to explain what the condition is all about.This is done in other to improove the awareness of the condition inother to reduce or stop spiritual taughts that clearly have nothing to do with the condition and that brings nothing else but harm to the family and the victims preventing them from a social intergration. 

* Finally he tires to figure outthe reasons  why the condition was kept so unknown by the general public and comes out with the hypothesis that may be the parents used to hide their kids from the society in other to avoid judgments for something they didn't commited



## Conclusions/ discovery	

I can conclude that it is very important for all us to manage the way we treat DS victims and their relatives




## Remaining questions	

has the name for DS in sawhili proposed by the woman been acknwoledged?





